# https://taskfile.dev

version: "3"

vars:
  CURRENT_DIR: /models/easy-ship-model

tasks:
  easyShip_2022-03-23:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}easyShip_2022-03-23 -i ./easyShip_2022-03-23.json
    silent: true
