# https://taskfile.dev

version: "3"

vars:
  CURRENT_DIR: /models/replenishment-api-model

tasks:
  replenishment-2022-11-07:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}replenishment-2022-11-07 -i ./replenishment-2022-11-07.json
    silent: true
