# https://taskfile.dev

version: "3"

vars:
  CURRENT_DIR: /models/catalog-items-api-model

tasks:
  catalogItemsV0:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}catalogItemsV0 -i ./catalogItemsV0.json
    silent: true

  catalogItems_2020-12-01:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - echo "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}catalogItems_2020-12-01 -i ./catalogItems_2020-12-01.json
    silent: true

  catalogItems_2022-04-01:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}catalogItems_2022-04-01 -i ./catalogItems_2022-04-01.json
    silent: true
