# https://taskfile.dev

version: "3"

vars:
  CURRENT_DIR: /models/reports-api-model

tasks:
  reports_2020-09-04:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}reports_2020-09-04 -i ./reports_2020-09-04.json
    silent: true

  reports_2021-06-30:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}reports_2021-06-30 -i ./reports_2021-06-30.json
    silent: true
