# https://taskfile.dev

version: "3"

vars:
  CURRENT_DIR: /models/authorization-api-model

tasks:
  aplusContent:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - echo "No API Content"
    silent: true
