# https://taskfile.dev

version: "3"

vars:
  CURRENT_DIR: /models/data-kiosk-api-model

tasks:
  dataKiosk_2023-11-15:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}dataKiosk_2023-11-15 -i ./dataKiosk_2023-11-15.json
    silent: true
