# https://taskfile.dev

version: "3"

vars:
  CURRENT_DIR: /models/fulfillment-outbound-api-model

tasks:
  fulfillmentOutbound_2020-07-01:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}fulfillmentOutbound_2020-07-01 -i ./fulfillmentOutbound_2020-07-01.json
    silent: true
