# https://taskfile.dev

version: "3"

vars:
  CURRENT_DIR: /models/product-fees-api-model

tasks:
  productFeesV0:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}productFeesV0 -i ./productFeesV0.json
    silent: true
