# https://taskfile.dev

version: "3"

vars:
  CURRENT_DIR: /models/fulfillment-inbound-api-model

tasks:
  fulfillmentInboundv2024-03-20:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}fulfillmentInboundv2024-03-20 -i ./fulfillmentInboundv2024-03-20.json
    silent: true

  fulfillmentInboundV0:
    dir: "{{.USER_WORKING_DIR}}{{.CURRENT_DIR}}"
    cmds:
      - java -jar "{{.USER_WORKING_DIR}}{{.SWAGGER_JAR}}" generate -l python -t {{.USER_WORKING_DIR}}{{.PATH_TO_MUSTACHE}} -D packageName=swagger_client -o {{.USER_WORKING_DIR}}{{.OUTPUT_PATH}}fulfillmentInboundV0 -i ./fulfillmentInboundV0.json
    silent: true
